name: CI/CD

on:
  push:
    branches: 
      - Production
jobs:
  CI-Pipeline:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./src/Coworking.Backend
          file: ./src/Coworking.Backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: naendi/spacecloud:backend
      -
        name: Build and push Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./src/Coworking.Frontend
          file: ./src/Coworking.Frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: naendi/spacecloud:frontend
        
  CD-Pipeline:
    needs: [CI-Pipeline]
    runs-on: ubuntu-latest
    steps:
     - 
      name: SSH Docker-Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /app
          docker-compose down
          docker rmi $(docker images -q)
          docker-compose up -d --build 
          
     
          
